namespace: prod

replicaCount: 3

image:
  repository: raman430/myservice
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 5000

serviceAccount:
  create: true
  automount: true
  annotations: {}
  
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000
  containerPort: 5000

ingress:
  enabled: true
  hostname: prod.myservice.local
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: prod.myservice.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
