apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
  namespace: nonexistent-ns
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "10Gi"
          cpu: "1"
